### ISSUE TITLE
Feature: Scroll to top button to be added

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/LGBTQ-definitions#1]
### Type of feature

✨ Feature

### Current behavior

- there is no scroll to top

### Suggested solution

- implement it using primeng button `p-button`
- to be implemented in the `app.component.ts`
- the way it has been implemented in other projects is using the `viewportScroller`

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()
- [ ] No

**Comment by ParthJohri** [comment]
@monacodelisa I have implemented the Scroll to Top Button [PR](https://github.com/monacodelisa/LGBTQ-definitions/pull/7), please review.
