### ISSUE TITLE
Feature: Make the search work 

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/LGBTQ-definitions#2]
### Type of feature

✨ Feature

### Current behavior

I have not implemented the search functionality at this point

## Prerequisite Missing
- structure adjustments could be made since the searchbar is in the sidenav
- there is no relation between the components right now searchbar is in the `header` component and populated results are in the `home` component

what I am considering

Option 1: maintain the current structure and use behavior subject or a signal to pass along search term
Option 2: restructure in a way that there is a child - parent relationship, which will include:
- moving header & sidenav all in the `app.component.ts` and loading `home` as a child component
- of course that would also mean that I need either setup conditional rendering for the `router-outlet` or create a layout for the pages and make the needed adjustments in `app.routes.ts`

### Additional context

again the main idea behind keeping this open source is so that new terms can be added, my availability to devote time to this project is limited

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()
- [ ] No

**Comment by ParthJohri** [comment]
@monacodelisa can you please assign this issue as well?

I have come across this blog https://dev.to/idrisrampurawala/creating-a-search-filter-in-angular-562d, and would be implementing it in that way.

Or I also thought of this way of implementation:-
1. LGBTQTerm[] would be storing the json, so I would be creating a hashmap or a trie and try to look for the names in the json file to match with the keyword.
2. Creating searchComponent for it, to abstract the logic.
3. Implementing the scroll to the card feature where in I will scroll down to the card which contains the term definition.
 
 Since, I am just starting off with learning angular so would like to know some suggestions for it.

**Comment by monacodelisa** [comment]
@ParthJohri cool I will assign you this issue, now my thoughts:

- it is very cool that you did a search for it and found a nice implementation 

The implementation that you found is ok, but here are few things to consider: 

- this is a bit of an outdated implementation, it shows you a way to handle the search functionality in a `modular` angular app while this one is a `standalone` app

Standalone apps were introduced in Angular v15 and they do not include `app.module.ts` so even if you choose this implementation some adjustments will need to be done to make it work 

- it is a bit of a tangled way, there are more straightforward ways to do it 

here is another implementation to consider [homes app](https://github.com/monacodelisa/Angular-HomesApp/blob/1405d615496eb2f3943f274b753f8405a3563277/src/app/components/home/home.component.ts#L49)

But the truth is that I don't have a lot of time to devote to this project right now, maybe in few days I will, so in the mean time you can try whichever option you like, I don't have an exact preference and if the implementation works - I can merge it, but it is possible that it might be changed / improved in the future - especially if more terms & definitions are added 

So up to you :) go ahead and see what works out

**Comment by ParthJohri** [comment]
Thank you @monacodelisa for your suggestions, will look into the implementation and try to search more about it.

**Comment by ParthJohri** [comment]
Greetings @monacodelisa, I have added the search bar functionality (https://github.com/monacodelisa/LGBTQ-definitions/issues/2), if there is any suggestion to make it better, please let me, I will make the changes.
