### ISSUE TITLE
Feature: change the favicon with pride flag 

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/LGBTQ-definitions#4]
### Type of feature

✨ Feature

### Current behavior

- default angular favicon

### Suggested solution

- change with custom pride flag one
- possibly change site `<title>` to match heading too, to be `Terms & Definitions`

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()
- [ ] No

**Comment by ParthJohri** [comment]
Good morning @monacodelisa, I would like to work on this issue, can you please assign it?
Thank you!

**Comment by monacodelisa** [comment]
@ParthJohri sure thing you are assigned, keep in mind in Angular v18 the `favicon.ico` is in the `public` folder

**Comment by ParthJohri** [comment]
@monacodelisa I have made my changes, please review if there is any other change to be made, please let me know.

**Comment by monacodelisa** [comment]
@ParthJohri your PR is merged, thank you for the contribution :)
