### ISSUE TITLE
Bug: fix the width of the search bar in mobile view

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/LGBTQ-definitions#9]
### Describe the bug

This is not visible in the emulator but on actual mobile devices the search bar's width needs to be adjusted

![viber_image_2024-06-26_09-35-24-636](https://github.com/monacodelisa/LGBTQ-definitions/assets/64324417/444d8ae4-1a28-4a18-a799-1d5fca5835eb)

### Steps to reproduce

View only on actual mobile device not using the chrome dev tools emulator

corrected version should look more like this: 

![image](https://github.com/monacodelisa/LGBTQ-definitions/assets/64324417/69ec7683-b6e2-4d5d-bf6b-d32e240aa25a)

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

mobile device

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()
- [ ] No

**Comment by ParthJohri** [comment]
@monacodelisa, I have used the mobile device to test for the fix of the bug, also got to learn how to view an angular app on a mobile device.

**Comment by monacodelisa** [comment]
> @monacodelisa, I have used the mobile device to test for the fix of the bug, also got to learn how to view an angular app on a mobile device via this command `ng serve --host 0.0.0.0`

@ParthJohri cool :)
